name: Backend Tests

on: push

base: ubuntu:24.04

dependencies:
  php:
    version: "8.3"
  mysql:
    version: "5.7"
    username: "root"
    password: ""
    databases:
      - laravel

steps:
  watch(composer.lock,composer.json):
    composer install --no-progress --optimize-autoloader --apcu-autoloader

  watch(.env.example):
    cp .env.example .env
    && php artisan key:generate

  watch(routes/*.php):
    php artisan route:cache

  watch(database/migrations/*.php):
    php artisan migrate --force

max-processes-per-runner: 2
